### PR TITLE
Fix login form to use username instead of email

### PR DESCRIPTION
**Pull request by davidmturner**
Change the input field to receive a username instead of email. The authentication call is done with username and not the email address.

### CODE REVIEW

**Comment by jayair** [comment]
Hey @davidmturner, we technically want to create a form that takes the user's email as their username. Hence, the form takes an email and passes that in as the username to AWS Cognito. Unfortunately, I did a poor job of describing that upfront.

I just added some more context at the top of the login chapter to address that, let me know if that makes more sense. Here is the commit - c272cecb052e90ed2f77d016727c00c51074344f.

**Comment by davidmturner** [comment]
Ah, ok! That does make sense.

I haven't made it to the end of your content yet and I've been skimming at breakneck speed while repurposing existing assets that I had in AWS, and therefore bringing the possibility that I missed something or inherited something.

Might be worth checking that the create user CLI chapter used the same semantics of email for username; I'll go back myself and check once I've made it to the end! :)

**Comment by jayair** [comment]
Yeah you're right, the [Create Test User](https://github.com/AnomalyInnovations/serverless-stack-com/blob/master/_chapters/create-a-cognito-test-user.md) chapter needs an edit as well. We'll push some changes to that soon.

Thanks!

**Comment by jayair** [comment]
Closing this 👍

**Pull request closed without merging**
