### PR TITLE
Translated "Why create serverless apps?" to portuguese.

### PR DESCRIPTION
**Pull request by bernardobugmann**
There we are! After a long time busy 😋

### CODE REVIEW

**Comment by jayair** [comment]
Looks great! Thank you sir!

**Comment by jayair** [comment]
Do you want me to delete the branch as well? Or do you want to hang on to it?

**Comment by bernardobugmann** [comment]
Well, I will delete to get a fresh branch to work again c:

**Comment by mmalaquiasdev** [comment]
Hello @bernardobugmann,

Can I translate to Portuguese with you?

**Comment by jayair** [comment]
@mmalaquiasdev Thank you!!

**Comment by mmalaquiasdev** [comment]
Done. :)

It will be my first step in open source world *-*

**Pull request merged**
