### PR TITLE
add a translation to Korean Language

### PR DESCRIPTION
**Pull request by bsg-bob**
I can help with a Korean translation and if you have any ideas on how to do it let me know.
Thanks

### CODE REVIEW

**Comment by jayair** [comment]
@bsg-bob First of thank you very much!

You have most of it right, it just needs the original front matter from the chapter you are translating with the `lang:` attribute changed. And make sure it has the `ref:` attribute as well.

I'll try and add them for the ones you already translated.

Thanks again!

**Comment by jayair** [comment]
There is also the `description:` attribute in the front matter that you can translate if you get a chance. It is a short description of the chapter but if it is left out then it just takes the first few lines from the chapter.

**Comment by jayair** [comment]
Let me know once it is good to go let me know and I'll merge the PR.

**Comment by jayair** [comment]
Btw, we can merge and publish a couple of chapters at a time. So whenever you feel ready to publish a few of them together, let me know.

**Comment by bsg-bob** [comment]
It's OK, merge please!
Thanks

**Comment by bsg-bob** [comment]
It's OK, merge, pleases!
Thanks

**Comment by jayair** [comment]
Awesome! Merging.

Just a heads up, if you are copying the front matter from a chapter that doesn't have a `ref:` or `lang:` attribute, add it there as well. This is what shows the link on the original chapter to the translation.

**Comment by jayair** [comment]
@bsg-bob It is live! 🎉 

I clicked around to make sure the translations look okay. But have a look and let me know if something is off.

**Comment by jayair** [comment]
Tweeted it out as well - https://twitter.com/Anomaly_Inv/status/1133073945387786241

**Comment by bsg-bob** [comment]
> @bsg-bob It is live! 🎉
> 
> I clicked around to make sure the translations look okay. But have a look and let me know if something is off.

The "what is aws lambda" Korean page is missing. Please check.

**Comment by jayair** [comment]
Ah I see. Merged.

**Pull request merged**
