### PR TITLE
Change Class Component to Function Component

### PR DESCRIPTION
**Pull request by jwooo**
In my opinion, it should be changed class component to a function component.

### CODE REVIEW

**Comment by jayair** [comment]
Thank you for this! Would it be possible to update the repo that's attached to this as well?

https://github.com/AnomalyInnovations/serverless-stack-demo-user-mgmt-client

**Comment by jwooo** [comment]
of course.

**Comment by jayair** [comment]
We might have to revisit this because of the latest update we pushed out — https://discourse.serverless-stack.com/t/new-update-to-serverless-stack/1736/2

**Comment by jwooo** [comment]
okay i applied latest update.

**Comment by jayair** [comment]
Thanks @jwooo! Merged!

**Pull request merged**
