### PR TITLE
Fix IAM role configs

### PR DESCRIPTION
**Pull request by xushiyan**
To use valid ARNs so that visual editor won't complain as shown below.

- [x] Need to add wildcard for method and resource path (last 2 fields)
screen shot 2018-09-09 at 10 42 32 am

### CODE REVIEW

**Comment by jayair** [comment]
Hmm the API Gateway one makes sense. But the S3 one we need to make sure that the user only has access to his folder in the S3 bucket.

Btw, are these warnings or is it not allowing you to add the IAM policy?

**Comment by xushiyan** [comment]
@jayair You're right. The S3 access should be just set at object level; I was blindly trying to resolve the visual editor's warning, which might turn out to be [a bug](https://forums.aws.amazon.com/thread.jspa?threadID=282453).

These warnings are only shown in visual editor and editing in JSON works fine.

**Comment by jayair** [comment]
@xushiyan Thanks!

**Comment by xushiyan** [comment]
@jayair Not at all! Thank you for making this awesome tutorial.

**Pull request merged**
