### PR TITLE
Improvement/ebook

### PR DESCRIPTION
**Pull request by pepas24**
I finally could work more on this. I want to detail the better posible this topic because this aproach still needs improvements, but I think it's a good approximation to the final result.

These are the results for now:

PDF: https://drive.google.com/file/d/1WUqipyj1Dqt6u-GrW_00hD9UdKUX8pC2/view?usp=sharing
EPUB: https://drive.google.com/file/d/1xImlIMsnpeedZoM-1gTLob9o1bNdUeIz/view?usp=sharing

The main improvements are:

- Better sectioning of content (avoiding cuts)
- Chapter navigation in reader apps
- Smaller file size
- Epub expot
- Avaible to deploy with travis

I used [Pandoc](https://pandoc.org/), a library to convert different type of text files into others.

The template file for build the pdf it's a modiffied version of [@Wandmalfarbe](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/eisvogel.tex). In this same repository there are the instructions about how install Pandoc and use the template. Here also there is a `.travis` file that can be useful as reference for automated deployment.

In the `Makefile` and `build-book.rb` I leave comments for clarify all steps to the final result.

Due to the use of Jekyll for the site some chapters has html, Jekyll variables or other type of content don't supported by Pandoc, so I had to use regular expresions for replace especific content, but still need be improved.

Finally for the Ebup version, also can be builded with Pandoc, but still needs aditional metadata like cover images, authors, tags etc. styles etc.

Please give me your feedback about design aspects like color, fonts, code highlight, headers, table of contents etc.

### CODE REVIEW

**Comment by jayair** [comment]
@pepas24 Just a couple of things I noticed. They are pretty minor.

- I'm not sure if we can add a line above the link to comments at the end of each chapter. It might make it more clear to readers what it is.
- In some cases the text goes into the margins. For example, on page 235.
- Would it be possible to link to chapters from the Table of contents?

Other than that, this looks really good!

screen shot 2019-02-25 at 2 12 43 pm

**Comment by jayair** [comment]
Oh one other thing I forgot to mention. Some of our chapters have a link to the GitHub repo for the source at the end of the chapters. It's near the link to the comments. For example, at the bottom of this chapter - https://serverless-stack.com/chapters/deploy-again.html. Would it be possible to add this to the PDF?

**Comment by pepas24** [comment]
​@jayair Thanks for take the time to see the pdf

- Comments: Yes, we can add more content for clarify that section, here are some variations that I tested:

imagen

The last one it's using an additional package, but the result it's sweet!

- Cut text: I don't see this issue, appear to be only in the inline code so I'll research for a solution
- Links in content table: Yes, in fact it should work, maybe not directly in Drive, but I tested it in Firefox and Edege pdf readers, also in Acrobat Reader and it worked.
- Github source code: I don't noticed that type of content before, I haven't been in that chapter yet, but I think with a regular expresion or maybe better implementing someting like [this parser](https://github.com/waiting-for-dev/front_matter_parser) should be more easy to transform the content for pandoc. There is another content like that?
And here is and example of implementing the code links:

imagen

**Comment by jayair** [comment]
@pepas24 As always thanks for the effort!

> Comments

I like the last one as well!

> Links in content table

That's great that it works in other readers.

> Github Source Code

The design looks great. This is the only type of content like this. So whichever solution is easy for you, we can go with.

**Comment by pepas24** [comment]
Hi @jayair, [this](https://drive.google.com/open?id=1WUqipyj1Dqt6u-GrW_00hD9UdKUX8pC2) is the latest version of the PDF, for now the site variables are replaced with the correct values, the inline codes are wrapped now and the boxes with forum and code links are placed correctly.

But I have a problem with a regex that causes some links don't has been replaced properly, maybe you can help me.

Here is a sample [regexr.com/4a99r](regexr.com/4a99r) of what I'm doing. But that regex match two consecutive links as one.

**Comment by jayair** [comment]
@pepas24 Thanks for the hard work!

I'll take a look at the regex this weekend and get back to you.

**Comment by jayair** [comment]
Hey @pepas24 sorry for the super late reply.

Here are a couple of regexs that should help:

- This one grabs all chapter links https://regexr.com/4cb2h
- And this one grabs all links in general https://regexr.com/4cb2k

Let me know if you have any questions.

**Comment by jayair** [comment]
This is about to go live! Thanks @pepas24 & @fwang!

**Pull request merged**
