### PR TITLE
refactor: Ensure to use `change` image tag instead hardcoded image

### PR DESCRIPTION
**Pull request by preshetin**
Hey there. While making edits some time ago I noticed that the `CHANGE` utility image is hardcoded. To improve the author experience, I refactored it to use Jekyl's plugin system.

To find and replace throughout all files in `_chapters` folder , you may want to run this command inside project dir:
```
find _chapters \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i '' 's/<img class="code-marker" src="\/assets\/s\.png" \/>/\{%change%\}/g'
```
I didn't include the changes made by this command to make the code review simpler. However, feel free to run it yourself.

Hope this would add some value to this awesome guide.

### CODE REVIEW

**Comment by jayair** [comment]
Oh this is pretty cool. Thank you! I didn't know you could do that. Can we use it as `{% change %}` instead of `{%change%}`?

**Comment by preshetin** [comment]
Yes, absolutely. 

Also, if you would want to have additional space between this image and first paragraph word (eg `{% change %} Paragraph start`, instead of `{% change %}Paragraph start`), then some CSS adjustment would be needed (I can do it).

Let me know how you would like me to adjust this PR

**Comment by jayair** [comment]
@preshetin Oh that would be really cool! If you can handle the space that would be much better.

**Comment by jayair** [comment]
Going to try this in a dev branch!

**Comment by jayair** [comment]
Works like a charm. Thanks @preshetin!

**Pull request merged**
