### PR TITLE
[Translation] Setting up the Serverless Backend chapter to portuguese

### PR DESCRIPTION
**Pull request by IgorGRibeiro**
Translated the "Setting up the Serverless Backend" to portuguese.

### CODE REVIEW

**Comment by jayair** [comment]
Thank you for this! @bernardobugmann can you take a quick look and we'll merge it?

Here is the deployed PR: https://deploy-preview-361--serverless-stack.netlify.com

**Comment by IgorGRibeiro** [comment]
You're welcome. @jayair @bernardobugmann please take a look, give some feedback about the quality and if everything is good to go. After your feedback i'm planning to translate all the chapters.

**Comment by bernardobugmann** [comment]
@IgorGRibeiro Sorry to take so long to look this. Until tonight I will check if everything is ok and merge the PR.

Sorry again. This year was super busy to me :(

**Comment by bernardobugmann** [comment]
Everything looks great! 👍

**Pull request merged**
