### PR TITLE
Setting react

### PR DESCRIPTION
**Pull request by bsg-bob**
Add  "Setting up a React App"

### CODE REVIEW

**Comment by jayair** [comment]
@bsg-bob I think a couple of these have `lang:` set to `kr` instead of `ko`.

**Comment by bsg-bob** [comment]
Sorry, Fixed it

**Comment by jayair** [comment]
Hey @bsg-bob Isn't the right code `ko`? I think they all need to be `ko` not `kr` 😝

**Comment by bsg-bob** [comment]
Of course, **kr** is right, but confusingly I changed it because you asked me to do **ko** here.

```
eu-US
ko-KR
```

So, can I change the language to all the **ko** values?

**Comment by jayair** [comment]
Looks good! Thank you again!

**Comment by jayair** [comment]
Merged. Have a look and let me know if something looks off.

**Pull request merged**
