### PR TITLE
"Create an AWS Account" chapter translated to PT

### PR DESCRIPTION
**Pull request by leogonzalez**
Hi, 

my first PR to this repo - contributing to the translation efforts to PT (https://github.com/AnomalyInnovations/serverless-stack-com/issues/271)

Next PR I will translate more chapters, this was a very short one just to see If I'm on the correct workflow. 

Let me know if workflow it correct! Thanks

### CODE REVIEW

**Comment by jayair** [comment]
@leogonzalez Thank you!

We just need to add this to the english version of the chapter. This links all the different language versions together.

```
lang: en
ref: create-an-aws-account
```

**Comment by leogonzalez** [comment]
@jayair alright, now I got it! Let me know if you need anything else on this chapter

**Comment by bernardobugmann** [comment]
@leogonzalez everything looks fine. Thanks to using a new screenshot of the website in portuguese. This could help people to understand better 😄

**Comment by jayair** [comment]
@leogonzalez Thank you!

**Pull request merged**
